import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Restaurants from '../components/restaurantList'

export default function Home() {
  return (

    <div className={styles.container}>
      <Head>
        <title>Restaurants-Hub</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Restaurants-Hub!
        </h1>
        <Restaurants></Restaurants>
      </main>
    </div>
  )
}
